sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2 
- gem install tilt
- sudo pip install git+https://github.com/rdhyee/ebooklib.git
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git

- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt
- asciidoctor -a toc,idprefix=xx_,version=$VERSION -b xhtml5 -T ./asciidoctor-htmlbook/htmlbook-autogen/
  -d book book.asciidoc -o book.html
- git clone https://github.com/gitenberg-dev/HTMLBook

# make book.html available to jinja2 environment by putting it into templates
- cp book.html asciidoctor-htmlbook/gitberg-machine/templates/

- /usr/bin/python asciidoctor-htmlbook/gitberg-machine/machine.py -o . -m metadata.yaml book.html
- xsltproc -stringparam external.assets.list " " ./HTMLBook/htmlbook-xsl/epub.xsl book.html
- cp ./HTMLBook/stylesheets/epub/epub.css OEBPS
- if [ -e cover.jpg ]; then cp cover.jpg OEBPS/cover.jpg; fi
# look for first images directory and one found, copy over to ./OEBPS
- find . -name images -type d | head -n 1 | xargs -I {} mv {} ./OEBPS/
- zip -rX book.epub mimetype
- zip -rX book.epub OEBPS/ META-INF/
- if test -d "OEBPS/images/"; then zip -rX book.epub OEBPS/images/ ;fi
- mv book.epub The-Brothers-Karamazov.epub
- ebook-convert The-Brothers-Karamazov.epub The-Brothers-Karamazov.mobi
- xvfb-run ebook-convert The-Brothers-Karamazov.epub The-Brothers-Karamazov.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: VAhIW5Xqfxb2M/VF7sLQrODs57LtX+2bpztua9CTqMVxuea09UXhAryRugRKzqzor5NPV82j9NTirM82pMYBJxrW5+RjmiP6UePviaat/QVYWzvPlLpLVdMbq46Kiyn9DPbD+qmWiDbaIhXo7ZDv3wRMh/f69h04wtbbrWvA1GcDHNYv5tXAQHnZh+vSGvQBMvHsKIisp3xVB0mpKIHHhHgJ5LRXrqEcdA6kFf8QS5yp0aosvZXsc3VN/X4Lj0nstOeTJQzkIVHA4vLeNPyxLL4eUBto2+6Q3i/nuEbZrOFW0/vwQfAiP5w+yWwy0oEENKtAp6TRIZMhmtD1H8+gA0dExaGXIzq0oeNjOAzRWedzHHwn0DqlDP47NdjqI7vweMBhAiu5e22BaSt9YOHYeuaZ63Po2TaqctVh1TUsyxi9zcnyJ0J3G8teXpB5kV9/BRyXHCIaYIOx6QpJhHyZBteT6E4r7z7c+Hiq6OfG4vB+rEbArPrwi4aJ3U1hfA7pCbiJEbHmT3xUs9+5MTxqV7eLuaXj6eaLDJlVUUPs1H+RWOH32SxICOzLRFMxjjeEpqNoz+1jEKGGtMqUSQKG1+YvPZticnbVMkrSHSOMQMXf1Ofp1yXRLwipkIOJHAdO0j8PtNIRQNMkw23+6BihgZf8pOj71Wfparyof8BdvG8=
  file:
    - The-Brothers-Karamazov.epub
    - The-Brothers-Karamazov.mobi
    - The-Brothers-Karamazov.pdf
  "on":
    repo: GITenberg/The-Brothers-Karamazov_28054
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre